apiVersion: apps/v1
kind: Deployment
metadata:
  name: figure-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: figure-service
  template:
    metadata:
      labels:
        app: figure-service
    spec:
      containers:
        - name: figure-service
          image: figure-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: figure-config
                  key: db_host
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: figure-service
                  key: db_password
